src/djwitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home),
    url(r'^tweets/', include('tweets.urls', namespace='tweet')),
    url(r'api/tweets/', include('tweets.api.urls'), name='tweets-api')
]

src/tweets/api/urls.py
from django.conf.urls import url, include
from .views import TweetListAPIView, TweetCreateAPIView

urlpatterns = [
    url(r'^$', TweetListAPIView.as_view(), name='list'),
    url(r'^create$', TweetCreateAPIView.as_view(), name='list')    
]

src/tweets/urls.py
from django.conf.urls import url, include
from .views import TweetListView, TweetDetailView, TweetCreateView, TweetUpdateView

urlpatterns = [
    url(r'^$', TweetListView.as_view(), name='list'),
    url(r'^create$', TweetCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)$', TweetDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update$', TweetUpdateView.as_view(), name='update'),
    # url(r'^$', list_view, name='list'),  
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/tweets/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.CharField(max_length=140)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content
        
    def get_absolute_url(self):
        return reverse('tweet:detail', kwargs={'pk': self.pk})

src/tweets/forms.py
from django import forms
from .models import Tweet

class TweetFormModel(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder': "Your message", 'class': "form-control"}))
    class Meta:
        model = Tweet
        fields = [
            # 'user',
            'content',
        ]

    def clean_content(self, *args, **kwargs):
        content = self.cleaned_data.get('content')
        return content

src/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/djwitter/views.py
from django.shortcuts import render

def home(request):
    return render(request, template_name='home.html')

src/tweets/api/views.py
from rest_framework import generics
from rest_framework import permissions
from .serializer import TweetModelSerializer
from tweets.models import Tweet
from django.db.models import Q


class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer

    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all().order_by('-timestamp')
        print(self.request.GET)
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            )
        return qs


class TweetCreateAPIView(generics.CreateAPIView):
    serializer_class = TweetModelSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

src/tweets/views.py
from django.shortcuts import render, get_object_or_404
from .models import Tweet
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .forms import TweetFormModel
from django.forms.utils import ErrorList
from django import forms
from django.db.models import Q
from .mixins import UserOwnerMixin
from django.urls import reverse_lazy

def list_view(request):
    object_list = Tweet.objects.all()
    return render(request, 'tweets/list_view.html', {'object_list': object_list}) 

def detail_view(request, id=1):
    object = Tweet.objects.get(id=id)
    return render(request, 'tweets/detail_view.html', {'object': object}) 

class TweetListView(ListView):
    
    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all()
        print(self.request.GET)
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                    Q(content__icontains=query) |
                    Q(user__username__icontains=query)
                    )
        return qs

    def get_context_data(self):
        context = super().get_context_data()
        context['form_content'] = TweetFormModel()
        context['submit_url'] = reverse_lazy('tweet:create')
        context['btn_value'] = "Submit"
        return context
            
class TweetDetailView(DetailView):
    # queryset = Tweet.objects.all()
    template_name = 'tweets/tweet_detail.html'
    def get_object(self):
        # return Tweet.objects.get(id=self.kwargs.get('pk'))
        return get_object_or_404(Tweet, pk=self.kwargs.get('pk'))
    
class TweetCreateView(CreateView):
    form_class = TweetFormModel
    template_name = 'tweets/tweet_create.html'
    # success_url = '/tweets'

    def form_valid(self, form):
        if self.request.user.is_authenticated():
            form.instance.user = self.request.user
            return super().form_valid(form)
        else:
            form._errors[forms.forms.NON_FIELD_ERRORS] = ErrorList(["User must be logged in"])
            return self.form_invalid(form)

class TweetUpdateView(UserOwnerMixin, UpdateView):
    form_class = TweetFormModel
    template_name = 'tweets/tweet_update.html'
    queryset = Tweet.objects.all()
    success_url = '/tweets'

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="/static/bootstrap.min.css">
  <link rel="stylesheet" href="/static/style.css">
  <title>Document</title>
</head>
<body>
  {% include "partials/navbar.html" %}
  <div class="container">
    <div class="row">
      <div class="col">
      </div>
    </div>
    <div class="row">
      {% block content %}
      
      {% endblock content %}
    </div>    
  </div>
  <script src="/static/jquery-3.2.1.min.js"></script>
  <script src="/static/bootstrap.min.js"></script>
  <script src="/static/popper.min.js"></script>
  {% block scripts %}
    <script>
      $(function(){
        var search_input = $('input[name="q"]');
        
        $(search_input).keyup(function(event){
          console.log($(search_input).val());

        });
        
      });
    </script>
  {% endblock scripts %}
</body>
</html>

src/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="/static/bootstrap.min.css">
  <link rel="stylesheet" href="/static/style.css">
  <title>Document</title>
</head>
<body>
  test stuff
  <script src="/static/jquery-3.3.1.slim.min.js"></script>
  <script src="/static/bootstrap.min.js"></script>
  <script src="/static/popper.min.js"></script>
</body>
</html>

src/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="row w-100">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li> -->
        </ul>
        {% include "tweets/search_form.html" %}
      </div>
    </div>
  </div>
</nav>

src/tweets/templates/tweets/form.html
<form {% if form_id %} id="create_form" {% endif %} action="{{submit_url}}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value={{btn_value}} class="btn btn-primary">
  <span class="chars_left">140</span>
</form>

src/tweets/templates/tweets/search_form.html
<form action="{% url 'tweet:list' %}" method="get" class="form-inline my-2 my-lg-0">
  <input name="q" value="{{request.GET.q}}" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

src/tweets/templates/tweets/tweet_create.html
{% include "tweets/form.html" with form=form btn_value="Tweet" %}

src/tweets/templates/tweets/tweet_detail.html
{{ object }}
{{ object.user }}

src/tweets/templates/tweets/tweet_list.html
{% extends "base.html" %}
{% block content %}
  <!-- {% include "tweets/search_form.html" %} -->
  <div class="col-sm-3">
    {{request.user}}
  </div>
  <div class="col-sm-9">
    {% include "tweets/form.html" with form=form_content form_id="form_id"%}
    <hr />
    <div id="tweets_container">

    </div>
    {% comment %} {% for object in object_list %}
      <div class="media">
        <div class="media-body">
          <h5 class="mt-0">{{object.user}}</h5>
          <p>{{object.content}}</p>
          <p class="mb-0">{{object.updated }} | <a href="{{ object.get_absolute_url}}">View</a></p>
        </div>
      </div>
      <hr class="w-100" />
    {% empty %}
      <div class="col-12 text-center">
        {% if request.GET.q %}
          No matches found
        {% else %}
          No tweets yet
        {% endif %}
      </div>
    {% endfor %} {% endcomment %}
  </div>
{% endblock content %}

{% block scripts %}
  {{block.super}}
  <script>
    $(function(){
      //Find query string value by name 
      function getParameterByName(name, url) {
        if (!url) url = window.location.href;
        name = name.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, " "));
      }
      //Append tweets to page via ajax
      function parseTweets(data, prepend=false){
        let htmlContent = function(value){
          return `<div class="media">
            <div class="media-body">
              <h5 class="mt-0">${value.user.username}</h5>
              <p>${value.content}</p>
              <p class="mb-0">${value.timesince} | <a href="#">View</a></p>
            </div>
          </div>
          <hr class="w-100" />`
        };
        if(prepend){
          $('#tweets_container').prepend(htmlContent(data));
        }else if(!data.length){
          $('#tweets_container').append("No tweets to display");
        }else {
          console.log('htmlContent : '+ JSON.stringify(data));
          
          $.each(data, function(key, value){
            console.log('key '+key+' value '+value.content)
            $('#tweets_container').append(htmlContent(value));
          });
          
        }
      }
      //Get tweets from the backend
      function fetchTweets(){
        $.ajax({
          method: 'GET',
          url: '/api/tweets',
          data: {
            'q': query
          },
          success: function(data){
            parseTweets(data)
            
            console.log('data '+ data.length);
          },
          error: function(data){
            console.log("error");
            console.log(data);
          }
        });
      }
      query = getParameterByName('q');
      fetchTweets();
      

      $('#create_form').submit(function(event){
        event.preventDefault();
        $.ajax({
          method: 'POST',
          url: '/api/tweets/create',
          data: $(this).serialize(),
          success: function(data){
            parseTweets(data, true);
            console.log('submit success : '+ JSON.stringify(data));
          },
          error: function(data){
            console.log("error");
            console.log(data);
          }
        })
        console.log($(this).serialize());
      });

      $('#create_form textarea').keyup(function(event){
        console.log(($(this).val()).length);
        $('.chars_left').text(140-($(this).val()).length)
        if( (140-($(this).val()).length) < 0 ){
          event.preventDefault();
          return;
        }
      });

    });
  </script>
{% endblock scripts %}

src/tweets/templates/tweets/tweet_update.html
{% include "tweets/form.html" with form=form btn_value="Tweet" %}